sudo: false
dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - develop
    - test

cache:
  directories:
    - $HOME/.composer/cache

services:
  - mysql

matrix:
  include:
    - php: 7.1
      env: WP_VERSION=master
    - php: 7.2
      env: WP_VERSION=master

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - bash tests/bin/install-wp-tests.sh wordpress_test root '' localhost latest
  - composer global require "phpunit/phpunit=4.8.*|5.7.*"

script:
  - phpunit
  - WP_MULTISITE=0 phpunit